/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * clientes.java
 *
 * Created on 09-abr-2013, 18:07:11
 */
package Formulario;

import claseConectar.conectar;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class clientes extends javax.swing.JInternalFrame {
    DefaultTableModel model;

    /** Creates new form clientes */
    public clientes() {
        initComponents();
        mostrarclientes("");
    }
   void buscar(String valor){
        
        String[]titulos={"Codigo","Nombre","Cedula","Tienda","Barrio","Telefono","direcion","Codigo Vendedor","Correo","Exhibidor","Colgaderas","Otros" } ;  
        String []Registros= new String[12];
       
        model=new DefaultTableModel(null,titulos);
      
        String Sql="SELECT * FROM cliente where nombre LIKE '%"+valor+"%'";
         try {
             Statement st = cn.createStatement();
             ResultSet rs = st.executeQuery(Sql);
             while(rs.next())
             { 
                  Registros[0]= rs.getString("cod_cli");
                  Registros[1]= rs.getString("nombre");
                  Registros[2]= rs.getString("tienda"); 
                  Registros[3]= rs.getString("barrio"); 
                  Registros[4]= rs.getString("telefono");
                  Registros[5]= rs.getString("direccion");
                  Registros[6]= rs.getString("correo");
                  Registros[7]= rs.getString("cedula");         
                  Registros[8]= rs.getString("vendedor_idvendedor");         
                  Registros[9]= rs.getString("Colgadera");         
                  Registros[10]= rs.getString("exhibidor");         
                  Registros[11]= rs.getString("Otros"); 
                 model.addRow(Registros);
             } 
             tbclientes.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    void mostrarclientes(String valor) {
        String mostrar="SELECT     * FROM cliente ";
//    String mostrar="select * from cliente, sugerencia ";
    String []titulos={"Codigo","Nombre","Tienda","Barrio","Telefono","Direccion","Correo","Cedula ","Vendedor","Colgadera","Exhibidor","Otros"};
    String []Registros=new String[12];
    model= new DefaultTableModel(null,titulos);
  
        try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
             
              while(rs.next())
              {
                  Registros[0]= rs.getString("cod_cli");
                  Registros[1]= rs.getString("nombre");
                  Registros[2]= rs.getString("tienda"); 
                  Registros[3]= rs.getString("barrio"); 
                  Registros[4]= rs.getString("telefono");
                  Registros[5]= rs.getString("direccion");
                  Registros[6]= rs.getString("correo");
                  Registros[7]= rs.getString("cedula");         
                  Registros[8]= rs.getString("vendedor_idvendedor");         
                  Registros[9]= rs.getString("Colgadera");         
                  Registros[10]= rs.getString("exhibidor");         
                  Registros[11]= rs.getString("Otros");         
                          
                  model.addRow(Registros);
                   
              }
              tbclientes.setModel(model); 
        } catch (SQLException ex) {
            Logger.getLogger(clientes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    
  } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbus = new javax.swing.JButton();
        txtbus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        Btnregistrar = new javax.swing.JButton();

        mnenviar.setText("Enviar Datos");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setText("Buscar Cliente:");

        btnbus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Search.png"))); // NOI18N
        btnbus.setText("Mostrar Todo");
        btnbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusActionPerformed(evt);
            }
        });

        txtbus.setText(" ");
        txtbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusActionPerformed(evt);
            }
        });
        txtbus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusKeyReleased(evt);
            }
        });

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbclientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbclientes);

        Btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/clients.png"))); // NOI18N
        Btnregistrar.setText("Registrar Clientes");
        Btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btnregistrar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbus)
                    .addComponent(Btnregistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusActionPerformed
// TODO add your handling code here:
    buscar("");
}//GEN-LAST:event_btnbusActionPerformed

private void txtbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtbusActionPerformed

private void txtbusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusKeyReleased
// TODO add your handling code here:
    buscar(txtbus.getText());
}//GEN-LAST:event_txtbusKeyReleased

private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed
// TODO add your handling code here:
    String cod="",nom="",barrio="",colgadera="",tienda="",direccion="",exhibidor="",vendedor="",otros="",telefono="";
    int fila = tbclientes.getSelectedRow();
    try {
        if(fila==-1)
        {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");
                  
        }
        else
        { 
         cod =(String) tbclientes.getValueAt(fila, 0);
         nom =  (String)tbclientes.getValueAt(fila, 1);
         tienda =  (String)tbclientes.getValueAt(fila, 2);
         barrio =  (String)tbclientes.getValueAt(fila, 3);
         telefono=  (String)tbclientes.getValueAt(fila, 4);
         direccion=  (String)tbclientes.getValueAt(fila, 5);
         vendedor=  (String)tbclientes.getValueAt(fila, 8);
         colgadera =  (String)tbclientes.getValueAt(fila, 9); 
         otros=  (String)tbclientes.getValueAt(fila, 11);
         
         
         Factura1.txtcodigo.setDisabledTextColor(Color.blue);
         Factura1.txtcodigo.setText(cod);         
                  
         Factura1.txtnombre.setDisabledTextColor(Color.blue);
         Factura1.txtnombre.setText(nom);         

         Factura1.txtbarrio.setDisabledTextColor(Color.blue);
         Factura1.txtbarrio.setText(barrio);
         Factura1.txtcolgadera.setDisabledTextColor(Color.blue);
         Factura1.txtcolgadera.setText(colgadera);
         Factura1.txttienda.setDisabledTextColor(Color.blue);
         Factura1.txttienda.setText(tienda);
         Factura1.txtdir.setDisabledTextColor(Color.blue);
         Factura1.txtdir.setText(direccion);
         Factura1.txttelefono.setDisabledTextColor(Color.blue);
         Factura1.txttelefono.setText(exhibidor);
         Factura1.txtvendedor.setDisabledTextColor(Color.blue);
         Factura1.txtvendedor.setText(vendedor);
         Factura1.txtotrosarea.setDisabledTextColor(Color.blue);
         Factura1.txtotrosarea.setText(otros);
         Factura1.txttelefono.setText(telefono);
         Factura1.txtotrosarea.setDisabledTextColor(Color.blue);
         this.dispose();
         
        }
    } catch (Exception e) {
        System.out.println("Formulario.clientes.mnenviarActionPerformed()"+e );
    }
}//GEN-LAST:event_mnenviarActionPerformed

private void BtnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnregistrarActionPerformed
// TODO add your handling code here:
    try {
        IngresoCliente ingcli= new IngresoCliente();
        ventanaadmin.jdpescritorio.add(ingcli);
        ingcli.toFront();
        ingcli.setVisible(true);
        this.dispose();
        
    } catch (Exception e) {
    }
    
        
    
    
    
}//GEN-LAST:event_BtnregistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnregistrar;
    private javax.swing.JButton btnbus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnenviar;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTextField txtbus;
    // End of variables declaration//GEN-END:variables
    conectar cc= new conectar();
    Connection cn = cc.conexion();
}
